#!/usr/bin/env bash
# Usage: ./deploy/deploy_host_ssh.sh <ssh-alias>
# Expects:
#   - SSH config alias already configured (done by CI)
#   - root .env already generated (done by CI)
# Steps:
#   1. Clone/fetch/reset the git repo on the server
#   2. Upload .env
#   3. Restart backend via docker compose

set -euo pipefail

readonly DEFAULT_REMOTE_DIR="/root/MoneyApp"
readonly DEPLOY_REPO_URL="https://github.com/vees1de/MoneyApp.git"
readonly DEPLOY_GIT_REF="main"

usage() {
  cat <<'EOF'
Usage:
  ./deploy/deploy_host_ssh.sh <ssh-alias>

Expects .env to be present in the repo root (generated by CI).
EOF
}

SSH_ALIAS="${1:-}"
REMOTE_DIR="${DEFAULT_REMOTE_DIR}"

if [[ -z "${SSH_ALIAS}" ]]; then
  usage
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

# ── Validate ───────────────────────────────────────────────────────────────
for cmd in ssh scp; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "missing required command: ${cmd}" >&2
    exit 1
  fi
done

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "missing ${ENV_FILE}. It should be generated by CI before calling this script." >&2
  exit 1
fi

# ── Sync git repo on server ────────────────────────────────────────────────
echo ">>> syncing git repo on ${SSH_ALIAS}:${REMOTE_DIR}"
ssh "${SSH_ALIAS}" \
  "REMOTE_DIR='${REMOTE_DIR}' DEPLOY_REPO_URL='${DEPLOY_REPO_URL}' DEPLOY_GIT_REF='${DEPLOY_GIT_REF}' bash -se" <<'REMOTE'
set -euo pipefail

if ! command -v git >/dev/null 2>&1; then
  echo "git is required on the server" >&2
  exit 1
fi

mkdir -p "${REMOTE_DIR}"

if [[ -d "${REMOTE_DIR}/.git" ]]; then
  echo "  updating existing git checkout"
  git -C "${REMOTE_DIR}" remote set-url origin "${DEPLOY_REPO_URL}"
else
  existing_entry=$(
    find "${REMOTE_DIR}" -mindepth 1 -maxdepth 1 \
      ! -name '.env' \
      ! -name '.env.*' \
      -print -quit
  )
  if [[ -n "${existing_entry}" ]]; then
    echo "target directory ${REMOTE_DIR} is not empty and is not a git repository" >&2
    echo "move it away or clean it manually before the first git-based deploy" >&2
    exit 1
  fi

  echo "  cloning repository"
  git clone --branch "${DEPLOY_GIT_REF}" --single-branch "${DEPLOY_REPO_URL}" "${REMOTE_DIR}"
fi

git -C "${REMOTE_DIR}" fetch --prune origin
git -C "${REMOTE_DIR}" checkout -B "${DEPLOY_GIT_REF}" "origin/${DEPLOY_GIT_REF}"
git -C "${REMOTE_DIR}" reset --hard "origin/${DEPLOY_GIT_REF}"
git -C "${REMOTE_DIR}" clean -fd -e frontend/dist
REMOTE

# ── Upload .env ────────────────────────────────────────────────────────────
echo ">>> uploading .env"
scp "${ENV_FILE}" "${SSH_ALIAS}:${REMOTE_DIR}/.env"

# ── Restart backend on server ──────────────────────────────────────────────
echo ">>> restarting backend"
ssh "${SSH_ALIAS}" "REMOTE_DIR='${REMOTE_DIR}' bash -se" <<'REMOTE'
set -euo pipefail
cd "${REMOTE_DIR}"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required on the server" >&2
  exit 1
fi

echo "  rebuilding + restarting backend container"
if ! docker compose up --build -d backend; then
  echo "--- migrate logs ---" >&2
  docker compose logs --tail=80 migrate >&2
  echo "--- backend logs ---" >&2
  docker compose logs --tail=40 backend >&2
  exit 1
fi

echo "  waiting for healthcheck"
for i in $(seq 1 30); do
  status=$(docker compose ps --format '{{.Health}}' backend 2>/dev/null || true)
  if [ "${status}" = "healthy" ]; then
    echo "  backend is healthy"
    break
  fi
  if [ "${i}" -eq 30 ]; then
    echo "backend did not become healthy in time" >&2
    docker compose logs --tail=50 backend >&2
    exit 1
  fi
  sleep 2
done
REMOTE

echo ">>> deployment completed"
