#!/usr/bin/env bash
# Usage: ./deploy/deploy_host_ssh.sh <ssh-alias> [/opt/moneyapp]
# Expects:
#   - SSH config alias already configured (done by CI)
#   - deploy/.env.host already generated (done by CI)
# Steps:
#   1. Build frontend on CI runner
#   2. Sync code + frontend/dist to server
#   3. Upload .env
#   4. Restart backend via docker compose

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./deploy/deploy_host_ssh.sh <ssh-alias> [/opt/moneyapp]

Expects deploy/.env.host to be present (generated by CI).
EOF
}

SSH_ALIAS="${1:-}"
REMOTE_DIR="${2:-/opt/moneyapp}"

if [[ -z "${SSH_ALIAS}" ]]; then
  usage
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

# ── Validate ───────────────────────────────────────────────────────────────
for cmd in ssh scp tar node npm; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "missing required command: ${cmd}" >&2
    exit 1
  fi
done

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "missing ${ENV_FILE}. It should be generated by CI before calling this script." >&2
  exit 1
fi

# ── Build frontend locally (on CI runner) ──────────────────────────────────
echo ">>> building frontend"
cd "${REPO_ROOT}/frontend"
npm ci --prefer-offline
npm run build
cd "${REPO_ROOT}"

# ── Sync project to server ─────────────────────────────────────────────────
echo ">>> syncing project to ${SSH_ALIAS}:${REMOTE_DIR}"
ssh "${SSH_ALIAS}" "mkdir -p '${REMOTE_DIR}'"

tar \
  --exclude='.git' \
  --exclude='frontend/node_modules' \
  --exclude='backend/bin' \
  --exclude='.env' \
  -czf - \
  -C "${REPO_ROOT}" . \
  | ssh "${SSH_ALIAS}" "tar -xzf - -C '${REMOTE_DIR}'"

# ── Upload .env ────────────────────────────────────────────────────────────
echo ">>> uploading .env"
scp "${ENV_FILE}" "${SSH_ALIAS}:${REMOTE_DIR}/.env"

# ── Restart backend on server ──────────────────────────────────────────────
echo ">>> restarting backend"
ssh "${SSH_ALIAS}" "REMOTE_DIR='${REMOTE_DIR}' bash -se" <<'REMOTE'
set -euo pipefail
cd "${REMOTE_DIR}"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required on the server" >&2
  exit 1
fi

echo "  rebuilding + restarting backend container"
if ! docker compose up --build -d backend; then
  echo "--- migrate logs ---" >&2
  docker compose logs --tail=80 migrate >&2
  echo "--- backend logs ---" >&2
  docker compose logs --tail=40 backend >&2
  exit 1
fi

echo "  waiting for healthcheck"
for i in $(seq 1 30); do
  status=$(docker compose ps --format '{{.Health}}' backend 2>/dev/null || true)
  if [ "${status}" = "healthy" ]; then
    echo "  backend is healthy"
    break
  fi
  if [ "${i}" -eq 30 ]; then
    echo "backend did not become healthy in time" >&2
    docker compose logs --tail=50 backend >&2
    exit 1
  fi
  sleep 2
done
REMOTE

echo ">>> deployment completed"
