import type {
  DepartmentTrainingBudget,
  EmployeeTrainingQuota,
  TrainingExpense,
  DepartmentBudgetReportRow,
  CourseSpendReportRow,
  BudgetLimit,
} from './budget-limit.model';

const DEV_EMPLOYEES: EmployeeTrainingQuota[] = [
  {
    employeeId: 'user-1',
    employeeName: 'Иванов Алексей',
    employeeEmail: 'ivanov@company.ru',
    departmentId: 'dept-1',
    departmentName: 'Разработка',
    quotaAmount: 200_000,
    spentAmount: 125_000,
    reservedAmount: 20_000,
    usedAmount: 145_000,
    remainingAmount: 55_000,
    usagePercent: 73,
    status: 'attention',
  },
  {
    employeeId: 'user-2',
    employeeName: 'Петрова Мария',
    employeeEmail: 'petrova@company.ru',
    departmentId: 'dept-1',
    departmentName: 'Разработка',
    quotaAmount: 200_000,
    spentAmount: 80_000,
    reservedAmount: 0,
    usedAmount: 80_000,
    remainingAmount: 120_000,
    usagePercent: 40,
    status: 'healthy',
  },
  {
    employeeId: 'user-3',
    employeeName: 'Сидоров Дмитрий',
    employeeEmail: 'sidorov@company.ru',
    departmentId: 'dept-1',
    departmentName: 'Разработка',
    quotaAmount: 200_000,
    spentAmount: 200_000,
    reservedAmount: 0,
    usedAmount: 200_000,
    remainingAmount: 0,
    usagePercent: 100,
    status: 'over_limit',
  },
  {
    employeeId: 'user-4',
    employeeName: 'Козлова Анна',
    employeeEmail: 'kozlova@company.ru',
    departmentId: 'dept-1',
    departmentName: 'Разработка',
    quotaAmount: 250_000,
    spentAmount: 155_000,
    reservedAmount: 20_000,
    usedAmount: 175_000,
    remainingAmount: 75_000,
    usagePercent: 70,
    status: 'attention',
  },
  {
    employeeId: 'user-5',
    employeeName: 'Новиков Сергей',
    employeeEmail: 'novikov@company.ru',
    departmentId: 'dept-1',
    departmentName: 'Разработка',
    quotaAmount: 180_000,
    spentAmount: 60_000,
    reservedAmount: 0,
    usedAmount: 60_000,
    remainingAmount: 120_000,
    usagePercent: 33,
    status: 'healthy',
  },
];

const MARKETING_EMPLOYEES: EmployeeTrainingQuota[] = [
  {
    employeeId: 'user-6',
    employeeName: 'Волкова Елена',
    employeeEmail: 'volkova@company.ru',
    departmentId: 'dept-2',
    departmentName: 'Маркетинг',
    quotaAmount: 150_000,
    spentAmount: 55_000,
    reservedAmount: 35_000,
    usedAmount: 90_000,
    remainingAmount: 60_000,
    usagePercent: 60,
    status: 'attention',
  },
  {
    employeeId: 'user-7',
    employeeName: 'Морозов Андрей',
    employeeEmail: 'morozov@company.ru',
    departmentId: 'dept-2',
    departmentName: 'Маркетинг',
    quotaAmount: 150_000,
    spentAmount: 45_000,
    reservedAmount: 0,
    usedAmount: 45_000,
    remainingAmount: 105_000,
    usagePercent: 30,
    status: 'healthy',
  },
];

const SALES_EMPLOYEES: EmployeeTrainingQuota[] = [
  {
    employeeId: 'user-8',
    employeeName: 'Лебедева Ольга',
    employeeEmail: 'lebedeva@company.ru',
    departmentId: 'dept-3',
    departmentName: 'Продажи',
    quotaAmount: 120_000,
    spentAmount: 120_000,
    reservedAmount: 0,
    usedAmount: 120_000,
    remainingAmount: 0,
    usagePercent: 100,
    status: 'over_limit',
  },
  {
    employeeId: 'user-9',
    employeeName: 'Кузнецов Павел',
    employeeEmail: 'kuznetsov@company.ru',
    departmentId: 'dept-3',
    departmentName: 'Продажи',
    quotaAmount: 100_000,
    spentAmount: 35_000,
    reservedAmount: 0,
    usedAmount: 35_000,
    remainingAmount: 65_000,
    usagePercent: 35,
    status: 'healthy',
  },
];

const HR_EMPLOYEES: EmployeeTrainingQuota[] = [
  {
    employeeId: 'user-10',
    employeeName: 'Соколова Татьяна',
    employeeEmail: 'sokolova@company.ru',
    departmentId: 'dept-4',
    departmentName: 'HR',
    quotaAmount: 120_000,
    spentAmount: 42_000,
    reservedAmount: 28_000,
    usedAmount: 70_000,
    remainingAmount: 50_000,
    usagePercent: 58,
    status: 'healthy',
  },
];

export const MOCK_ALL_EMPLOYEES: EmployeeTrainingQuota[] = [
  ...DEV_EMPLOYEES,
  ...MARKETING_EMPLOYEES,
  ...SALES_EMPLOYEES,
  ...HR_EMPLOYEES,
];

export const MOCK_EXPENSES: TrainingExpense[] = [
  {
    id: 'exp-1', requestId: 'req-1', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-1', employeeName: 'Иванов Алексей', employeeEmail: 'ivanov@company.ru',
    courseTitle: 'Advanced Go Programming', providerName: 'Coursera',
    amount: 85_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-28T10:00:00Z', updatedAt: '2026-03-28T10:00:00Z',
  },
  {
    id: 'exp-2', requestId: 'req-2', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-1', employeeName: 'Иванов Алексей', employeeEmail: 'ivanov@company.ru',
    courseTitle: 'System Design Workshop', providerName: 'Udemy Business',
    amount: 60_000, currency: 'RUB', status: 'approved',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-15T14:30:00Z', updatedAt: '2026-03-15T14:30:00Z',
  },
  {
    id: 'exp-3', requestId: 'req-3', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-2', employeeName: 'Петрова Мария', employeeEmail: 'petrova@company.ru',
    courseTitle: 'Angular Advanced Patterns', providerName: 'Pluralsight',
    amount: 45_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-10T09:15:00Z', updatedAt: '2026-03-10T09:15:00Z',
  },
  {
    id: 'exp-4', requestId: 'req-4', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-2', employeeName: 'Петрова Мария', employeeEmail: 'petrova@company.ru',
    courseTitle: 'UX для разработчиков', providerName: 'Skillbox',
    amount: 35_000, currency: 'RUB', status: 'reserved',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-30T11:45:00Z', updatedAt: '2026-03-30T11:45:00Z',
  },
  {
    id: 'exp-5', requestId: 'req-5', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-3', employeeName: 'Сидоров Дмитрий', employeeEmail: 'sidorov@company.ru',
    courseTitle: 'Kubernetes in Production', providerName: 'Linux Foundation',
    amount: 95_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-02-20T08:00:00Z', updatedAt: '2026-02-20T08:00:00Z',
  },
  {
    id: 'exp-6', requestId: 'req-6', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-3', employeeName: 'Сидоров Дмитрий', employeeEmail: 'sidorov@company.ru',
    courseTitle: 'AWS Solutions Architect', providerName: 'AWS Training',
    amount: 105_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-01-15T13:00:00Z', updatedAt: '2026-01-15T13:00:00Z',
  },
  {
    id: 'exp-7', requestId: 'req-7', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-4', employeeName: 'Козлова Анна', employeeEmail: 'kozlova@company.ru',
    courseTitle: 'Engineering Management', providerName: 'Стратоплан',
    amount: 120_000, currency: 'RUB', status: 'approved',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-02-05T10:30:00Z', updatedAt: '2026-02-05T10:30:00Z',
  },
  {
    id: 'exp-8', requestId: 'req-8', departmentId: 'dept-2', departmentName: 'Маркетинг',
    employeeId: 'user-6', employeeName: 'Волкова Елена', employeeEmail: 'volkova@company.ru',
    courseTitle: 'Data-Driven Marketing', providerName: 'Нетология',
    amount: 55_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-03-01T09:00:00Z',
  },
  {
    id: 'exp-9', requestId: 'req-9', departmentId: 'dept-2', departmentName: 'Маркетинг',
    employeeId: 'user-6', employeeName: 'Волкова Елена', employeeEmail: 'volkova@company.ru',
    courseTitle: 'SEO Masterclass', providerName: 'Skillbox',
    amount: 35_000, currency: 'RUB', status: 'cancelled',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-02-15T16:00:00Z', updatedAt: '2026-02-28T10:00:00Z',
  },
  {
    id: 'exp-10', requestId: 'req-10', departmentId: 'dept-3', departmentName: 'Продажи',
    employeeId: 'user-8', employeeName: 'Лебедева Ольга', employeeEmail: 'lebedeva@company.ru',
    courseTitle: 'B2B Sales Mastery', providerName: 'SalesHacker',
    amount: 70_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-20T12:00:00Z', updatedAt: '2026-03-20T12:00:00Z',
  },
  {
    id: 'exp-11', requestId: 'req-11', departmentId: 'dept-3', departmentName: 'Продажи',
    employeeId: 'user-8', employeeName: 'Лебедева Ольга', employeeEmail: 'lebedeva@company.ru',
    courseTitle: 'Negotiation Skills', providerName: null,
    amount: 50_000, currency: 'RUB', status: 'cancelled',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-01-28T14:00:00Z', updatedAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'exp-12', requestId: 'req-12', departmentId: 'dept-4', departmentName: 'HR',
    employeeId: 'user-10', employeeName: 'Соколова Татьяна', employeeEmail: 'sokolova@company.ru',
    courseTitle: 'HR Analytics & People Data', providerName: 'Coursera',
    amount: 42_000, currency: 'RUB', status: 'completed',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-05T10:00:00Z', updatedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'exp-13', requestId: 'req-13', departmentId: 'dept-1', departmentName: 'Разработка',
    employeeId: 'user-5', employeeName: 'Новиков Сергей', employeeEmail: 'novikov@company.ru',
    courseTitle: 'Playwright E2E Testing', providerName: 'Test Automation University',
    amount: 60_000, currency: 'RUB', status: 'approved',
    budgetCheckStatus: 'within_budget', requiresAdditionalApproval: false,
    createdAt: '2026-03-25T15:00:00Z', updatedAt: '2026-03-25T15:00:00Z',
  },
];

const DEV_EXPENSES = MOCK_EXPENSES.filter((e) => e.departmentId === 'dept-1');
const MARKETING_EXPENSES = MOCK_EXPENSES.filter((e) => e.departmentId === 'dept-2');
const SALES_EXPENSES = MOCK_EXPENSES.filter((e) => e.departmentId === 'dept-3');
const HR_EXPENSES = MOCK_EXPENSES.filter((e) => e.departmentId === 'dept-4');

export const MOCK_DEPARTMENT_BUDGETS: DepartmentTrainingBudget[] = [
  {
    departmentId: 'dept-1', departmentName: 'Разработка',
    totalBudget: 2_400_000, spentAmount: 1_200_000, reservedAmount: 360_000,
    usedAmount: 1_560_000, remainingAmount: 840_000, usagePercent: 65,
    currency: 'RUB', status: 'attention',
    employees: DEV_EMPLOYEES, expenses: DEV_EXPENSES,
  },
  {
    departmentId: 'dept-2', departmentName: 'Маркетинг',
    totalBudget: 1_200_000, spentAmount: 380_000, reservedAmount: 100_000,
    usedAmount: 480_000, remainingAmount: 720_000, usagePercent: 40,
    currency: 'RUB', status: 'healthy',
    employees: MARKETING_EMPLOYEES, expenses: MARKETING_EXPENSES,
  },
  {
    departmentId: 'dept-3', departmentName: 'Продажи',
    totalBudget: 900_000, spentAmount: 575_000, reservedAmount: 100_000,
    usedAmount: 675_000, remainingAmount: 225_000, usagePercent: 75,
    currency: 'RUB', status: 'risk',
    employees: SALES_EMPLOYEES, expenses: SALES_EXPENSES,
  },
  {
    departmentId: 'dept-4', departmentName: 'HR',
    totalBudget: 600_000, spentAmount: 142_000, reservedAmount: 68_000,
    usedAmount: 210_000, remainingAmount: 390_000, usagePercent: 35,
    currency: 'RUB', status: 'healthy',
    employees: HR_EMPLOYEES, expenses: HR_EXPENSES,
  },
  {
    departmentId: 'dept-5', departmentName: 'Финансы',
    totalBudget: 800_000, spentAmount: 250_000, reservedAmount: 70_000,
    usedAmount: 320_000, remainingAmount: 480_000, usagePercent: 40,
    currency: 'RUB', status: 'healthy',
    employees: [], expenses: [],
  },
];

export const MOCK_DEPARTMENT_REPORTS: DepartmentBudgetReportRow[] = MOCK_DEPARTMENT_BUDGETS.map((d) => ({
  departmentId: d.departmentId,
  departmentName: d.departmentName,
  totalBudget: d.totalBudget,
  spentAmount: d.spentAmount,
  reservedAmount: d.reservedAmount,
  usedAmount: d.usedAmount,
  remainingAmount: d.remainingAmount,
  usagePercent: d.usagePercent,
  status: d.status,
  headcount: d.employees.length,
  activeRequests: d.expenses.filter((e) => e.status === 'reserved' || e.status === 'approved').length,
  currency: d.currency,
}));

export const MOCK_TOP_COURSES: CourseSpendReportRow[] = [
  { courseTitle: 'Engineering Management', totalAmount: 360_000, requestCount: 3, uniqueEmployees: 3, currency: 'RUB' },
  { courseTitle: 'AWS Solutions Architect', totalAmount: 315_000, requestCount: 3, uniqueEmployees: 3, currency: 'RUB' },
  { courseTitle: 'Kubernetes in Production', totalAmount: 285_000, requestCount: 3, uniqueEmployees: 3, currency: 'RUB' },
  { courseTitle: 'Advanced Go Programming', totalAmount: 255_000, requestCount: 3, uniqueEmployees: 3, currency: 'RUB' },
  { courseTitle: 'Data-Driven Marketing', totalAmount: 220_000, requestCount: 4, uniqueEmployees: 4, currency: 'RUB' },
  { courseTitle: 'B2B Sales Mastery', totalAmount: 210_000, requestCount: 3, uniqueEmployees: 3, currency: 'RUB' },
  { courseTitle: 'Angular Advanced Patterns', totalAmount: 180_000, requestCount: 4, uniqueEmployees: 4, currency: 'RUB' },
  { courseTitle: 'System Design Workshop', totalAmount: 180_000, requestCount: 3, uniqueEmployees: 3, currency: 'RUB' },
];

export const MOCK_BUDGET_LIMIT: BudgetLimit = {
  departments: MOCK_DEPARTMENT_BUDGETS,
  departmentReport: MOCK_DEPARTMENT_REPORTS,
  employeeReport: MOCK_ALL_EMPLOYEES.map((e) => ({
    employeeId: e.employeeId,
    employeeName: e.employeeName,
    departmentId: e.departmentId,
    departmentName: e.departmentName,
    quotaAmount: e.quotaAmount,
    spentAmount: e.spentAmount,
    reservedAmount: e.reservedAmount,
    usedAmount: e.usedAmount,
    remainingAmount: e.remainingAmount,
    usagePercent: e.usagePercent,
    status: e.status,
    activeRequests: 0,
  })),
  topCourses: MOCK_TOP_COURSES,
  history: MOCK_EXPENSES,
};
